---
- name: Install Amazon Linux extras for LAMP stack.
  shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

- name: Install LAMP packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  notify: Restart all LAMP services

- name: Place SSL/TLS certificate
  copy:
    src: localhost.crt
    dest: /etc/pki/tls/certs/localhost.crt
  notify: Restart all LAMP services

- name: Enable placed certificate for Apache 1/2
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateKeyFile .*$'
    replace: '#SSLCertificateKeyFile /etc/pki/tls/private/localhost.key'
- name: Enable placed certificate for Apache 2/2
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: 'SSLCertificateFile .*$'
    replace: 'SSLCertificateFile /etc/pki/tls/certs/localhost.crt'

- name: Update groups for user
  user:
    name: ec2-user
    groups: adm,wheel,systemd-journal,apache
    append: yes

- name: Configure /var/www/html directory permissions
  file:
    path: /var/www/html
    owner: ec2-user
    group: apache
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Ensure LAMP services are running
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ services }}"